from pathlib import Path
from html import escape
import shutil
from xml.sax.saxutils import escape as xml_escape

ROOT=Path(__file__).resolve().parent.parent
DIST=ROOT
ASSETS=DIST/'assets'
ASSETS.mkdir(parents=True,exist_ok=True)
# The published resume is already in assets/. Replace it there before publishing.


LINKEDIN='https://www.linkedin.com/in/tanmay-agrawal-23102320a/'
GITHUB='https://github.com/iamtanmayag'
EMAIL='tanmayagrawal2764@gmail.com'
SITE_URL='https://iamtanmayag.github.io'

ICONS={
'arrow': '<path d="M5 12h14M13 6l6 6-6 6"/>',
'arrow-up':'<path d="M7 17 17 7M7 7h10v10"/>',
'mail':'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>',
'github':'<path d="M9 19c-4.3 1.4-4.3-2.5-6-3m12 6v-3.9a3.5 3.5 0 0 0-1-2.7c3.3-.4 6.8-1.6 6.8-7.4a5.7 5.7 0 0 0-1.5-3.9 5.2 5.2 0 0 0-.1-3.8S17.9.1 15 2a14.5 14.5 0 0 0-8 0C4.1.1 2.8.3 2.8.3a5.2 5.2 0 0 0-.1 3.8A5.7 5.7 0 0 0 1.2 8c0 5.8 3.5 7 6.8 7.4a3.5 3.5 0 0 0-1 2.7V22" transform="translate(1 0) scale(.95)"/>',
'linkedin':'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M8 10v7m0-10v.1M12 17v-7m0 3a3 3 0 0 1 6 0v4"/>',
'download':'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',
'menu':'<path d="M4 7h16M4 12h16M4 17h16"/>',
'close':'<path d="M5 5 19 19M19 5 5 19"/>',
'copy':'<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/>',
'check':'<path d="m4 13 5 5L20 6"/>',
'sun':'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32 1.41 1.41M2 12h2m16 0h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/>',
'moon':'<path d="M20 15.2A8 8 0 0 1 8.8 4 8 8 0 1 0 20 15.2Z"/>',
'chevron':'<path d="m6 9 6 6 6-6"/>',
'back':'<path d="M19 12H5m6 6-6-6 6-6"/>',
}
def icon(name,size=18): return f'<svg class="icon" aria-hidden="true" width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">{ICONS[name]}</svg>'

CASES=[
 dict(slug='document-intelligence', category='PRODUCTION AI', number='01', name='Document intelligence, engineered for production', short='LLM-assisted insurance workflows built around the hard parts: imperfect documents, OCR latency, memory limits and validation.', stack=['Python','Azure OpenAI','Azure OCR','asyncio','AWS Lambda'], year='2024–26', contribution='Backend and AI-workflow engineering', theme='lime', problem='Insurance documents arrive in different layouts and formats, sometimes as large PDFs, nested email attachments or damaged files. Reliable extraction requires more than a model call: the document must be made usable, processing must finish within infrastructure limits and downstream data must be checked.', approach=[('Recover and prepare','Worked on PDF repair, OCR rotation and recursive parsing of email and archive attachments to make complex inputs usable.'),('Integrate AI','Built and maintained Azure OpenAI GPT-4o document extraction and classification workflows, connecting OCR outputs, client-specific handling and structured validation.'),('Design for limits','Optimized concurrent Azure OCR requests with asyncio.gather and page-level resource management to control peak memory use within Lambda.')], result='In an affected PDF rotation workflow, processing that could exceed Lambda’s 15-minute limit was reduced to approximately 1–2 minutes in observed runs.', responsibility='My work covered the backend workflows, integration, processing and validation. This is not a claim that I trained the model or developed every piece of core AI logic.', diagram=['Incoming documents','Repair + OCR','LLM integration','Validate + deliver']),
 dict(slug='webhook-modernization', category='BACKEND ARCHITECTURE', number='02', name='Rebuilding the enterprise webhook layer', short='An independently designed redesign of a legacy webhook service with clearer client boundaries and reliable failure handling.',stack=['Python','REST APIs','Redis','AWS','PostgreSQL'],year='2025–26',contribution='Independent architecture and implementation',theme='blue',problem='Enterprise clients require different payload contracts, authentication methods and delivery behaviors. The legacy service had accumulated coupling that made client-specific changes difficult to maintain.', approach=[('Design the boundaries','Designed a modular architecture with client-isolated flows and explicit interfaces instead of tightly coupled conditional paths.'),('Handle imperfect deliveries','Implemented validation and failure-handling paths for the kinds of webhook issues encountered in production.'),('Own the rollout','Implemented and reviewed the change, then closely monitored production behavior following deployment.')],result='The first week of production monitoring revealed no observed deployment-related defects. Approximately 40,000 lines were changed in total, including additions and removals.',responsibility='Independently owned the architecture and implementation. Client and internal service details are intentionally generalized.',diagram=['Client event','Tenant routing','Validate + process','Deliver / recover']),
 dict(slug='cross-region-migration',category='CLOUD & DATA',number='03',name='Moving production data without losing its identity',short='Application and data migration from AWS Mumbai to N. Virginia, with client IDs and billing consistency preserved.',stack=['AWS S3','PostgreSQL','AWS RDS','Python','SQL'],year='2025',contribution='Application changes and data migration',theme='peach',problem='US-based clients requested a US data region. Moving application data was complicated by region-dependent configurations and identifier mismatches that could break client-specific logic or billing.',approach=[('Decouple the region','Replaced hardcoded dependencies with environment-aware application configuration.'),('Protect the data model','Migrated client PostgreSQL and S3 data while accounting for conflicting IDs and billing-related records.'),('Verify each flow','Executed SQL checks and manually validated individual client workflows and services across the cutover.')],result='The transition was completed without customer-visible downtime in production observations.',responsibility='I owned internal code changes and data migration. An external infrastructure provider handled the underlying cloud architecture relocation.',diagram=['ap-south-1','App refactoring','Data + ID checks','us-east-1']),
 dict(slug='database-performance',category='DATABASE ENGINEERING',number='04',name='Faster queries. Exactly the same numbers.',short='A carefully validated PostgreSQL migration and performance effort where speed could never come at the expense of billing accuracy.',stack=['PostgreSQL','AWS RDS','SQL','Redis','EXPLAIN ANALYZE'],year='2025–26',contribution='Independent migration, optimization and validation',theme='lime',problem='Mixed UUID and text join keys introduced inefficient type casts; expensive queries and shared read/write load contributed to slow APIs. Incorrect results would have downstream billing consequences.',approach=[('Find the bottlenecks','Used EXPLAIN ANALYZE, Dalibo execution-plan visualization and RDS performance observations to understand expensive query paths.'),('Change the right layer','Implemented PostgreSQL schema and query changes, caching and separation of read and write workloads.'),('Test for correctness','Validated production-like data and manually checked affected client workflows and billing numbers before and after deployment.')],result='One affected API improved from approximately 10 seconds to around 30–40 ms after successive optimizations. The schema migration was observed in production without reported defects.',responsibility='I personally authored and executed the schema/query changes and performed the client-by-client validation.',diagram=['Observe query','Schema + index','Cache / isolate reads','Verify output']),
 dict(slug='notification-platform',category='EVENT-DRIVEN SYSTEMS',number='05',name='Notifications designed to expand',short='An extensible delivery system built around user-device mappings, scheduled workers and Firebase multicast notifications.',stack=['Firebase FCM','Celery','PostgreSQL','Python','Realtime Database'],year='2025–26',contribution='Independent system design and implementation',theme='blue',problem='The platform needed scheduled and targeted notifications while keeping device tokens, users and notification types organized for future expansion.',approach=[('Model subscriptions','Designed tables linking users, device tokens and notification types.'),('Orchestrate delivery','Used scheduled Celery workers to select the users and notifications that needed processing.'),('Deliver at scale','Integrated Firebase Cloud Messaging, multicast delivery and Firebase Realtime Database.')],result='Delivered a reusable foundation for current notification workflows and additional notification types in the future.',responsibility='I designed and implemented the full notification-system foundation during my full-time SDE role.',diagram=['Notification rule','Celery schedule','Token mapping','FCM delivery']),
 dict(slug='air-curtain-iot',category='FULL STACK · IOT',number='06',name='One control plane for air curtains across India',short='A paid, independently built web platform connecting a national air-curtain fleet to real-time monitoring and remote control.',stack=['React','Node.js','Express','DynamoDB','AWS IoT','MQTT'],year='2024',contribution='End-to-end software development and deployment',theme='peach',problem='An engineering company wanted to monitor the operating data of its air curtains distributed across India and control devices from a central web portal.',approach=[('Build the portal','Developed the React interface and Node.js/Express backend for authenticated device management, telemetry and location-based filters.'),('Connect the devices','Implemented AWS IoT Core/MQTT publishing and subscriptions using certificates provided by the hardware team.'),('Make data actionable','Integrated DynamoDB-backed telemetry and remote-control workflows and collaborated with the professor and hardware team during integration.')],result='The platform was deployed as a paid company project and, according to the company engagement, is used to manage devices across India.',responsibility='I independently developed the software. Device firmware and hardware were owned by the hardware team.',diagram=['Web dashboard','AWS IoT Core','MQTT control','Devices + DynamoDB']),
]

def social_link(href,label,ic, extra=''):
 return f'<a href="{href}" target="_blank" rel="noopener noreferrer" class="social-link" aria-label="{label}">{icon(ic,18)}<span>{label}</span>{icon("arrow-up",14)}</a>'

def base(title, desc, body, page='home', canonical=''):
 page_url = SITE_URL.rstrip('/') + (canonical or '/') if page != '404' else ''
 canonical_html = f'<link rel="canonical" href="{escape(page_url,quote=True)}">' if page_url else ''
 og_url_html = f'<meta property="og:url" content="{escape(page_url,quote=True)}">' if page_url else ''
 robots = 'noindex, follow' if page == '404' else 'index, follow'
 return f'''<!doctype html><html lang="en" data-theme="dark"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0d1518">
<meta name="description" content="{escape(desc,quote=True)}"><meta name="robots" content="{robots}">{canonical_html}
<meta property="og:type" content="website">{og_url_html}<meta property="og:title" content="{escape(title,quote=True)}"><meta property="og:description" content="{escape(desc,quote=True)}"><meta property="og:image" content="{SITE_URL}/assets/social-preview.png"><meta name="twitter:card" content="summary_large_image">
<title>{escape(title)}</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/styles.css"><script src="/assets/site.js" defer></script>
</head><body data-page="{page}"><a href="#main" class="skip">Skip to content</a><div class="scroll-line" id="scroll-line" aria-hidden="true"></div>
<header class="site-header"><div class="header-inner wrap"><a class="brand" href="/" aria-label="Tanmay Agrawal homepage"><span class="brand-mark">t<span class="mark-dot">.</span>a</span><span class="brand-label">TANMAY AGRAWAL<br><small>ENGINEERING / INTELLIGENCE</small></span></a>
<nav class="desktop-nav" aria-label="Main navigation"><a href="/#work">Work</a><a href="/#approach">Approach</a><a href="/#about">About</a><a href="/#contact">Contact</a></nav>
<div class="header-actions"><button type="button" class="theme-toggle" aria-label="Switch theme" title="Switch theme">{icon('sun',18)}<span class="visually-hidden">Toggle color theme</span></button><a href="/assets/Tanmay_Agrawal_Resume.pdf" class="nav-resume" target="_blank" rel="noopener">Résumé {icon('arrow-up',15)}</a><button class="menu-button" type="button" aria-label="Open menu" aria-expanded="false">{icon('menu',22)}</button></div></div>
<nav class="mobile-nav" aria-label="Mobile navigation" hidden><a href="/#work">Work</a><a href="/#approach">Approach</a><a href="/#about">About</a><a href="/#contact">Contact</a><a href="/assets/Tanmay_Agrawal_Resume.pdf">Résumé ↗</a></nav></header>
<main id="main">{body}</main>
<footer class="footer"><div class="wrap footer-main"><div><a class="footer-brand" href="/">TA<span>.</span></a><p>Thoughtful engineering. Production reality.</p></div><div class="footer-links"><a href="{LINKEDIN}" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="{GITHUB}" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="mailto:{EMAIL}">Email ↗</a></div></div><div class="wrap footer-bottom"><span>© <span class="year">2026</span> Tanmay Agrawal</span><span>Built with care. No templates, no tracking.</span><a href="#main">Back to top ↑</a></div></footer>
</body></html>'''

WORKCARDS=''.join(f'''<a class="project-card theme-{x['theme']}" href="/work/{x['slug']}/" data-kind="{('ai' if 'AI' in x['category'] else 'systems' if x['category']!='FULL STACK · IOT' else 'product')}" aria-label="Read case study: {escape(x['name'])}"><div class="project-top"><span class="project-index">{x['number']} / {x['category']}</span><span class="project-out">{icon('arrow-up',19)}</span></div><div class="project-visual visual-{x['number']}" aria-hidden="true"><span class="visual-cross cross1">+</span><span class="visual-cross cross2">+</span><span class="visual-circle ring1"></span><span class="visual-circle ring2"></span><span class="visual-chip chip1">{escape(x['diagram'][0].upper())}</span><span class="visual-chip chip2">{escape(x['diagram'][-1].upper())}</span><span class="visual-track"></span></div><div class="project-copy"><h3>{escape(x['name'])}</h3><p>{escape(x['short'])}</p><div class="tag-row">{''.join('<span>'+escape(t)+'</span>' for t in x['stack'][:4])}</div></div><span class="project-read">Read the case study {icon('arrow',16)}</span></a>''' for x in CASES)

hero_diagram='''<div class="system-panel" aria-label="Interactive diagram of an AI document workflow"><div class="panel-head"><span class="terminal-dots"><i></i><i></i><i></i></span><span>PRODUCTION AI / REFERENCE FLOW</span><span class="panel-live"><i></i> SYSTEMS ONLINE</span></div><div class="panel-body"><div class="panel-caption"><span>ANATOMY OF A PIPELINE</span><span>SELECT A STAGE ↘</span></div><div class="pipeline-map"><div class="flow-rail" aria-hidden="true"></div>
<button class="flow-node active" data-stage="0" aria-pressed="true"><span class="flow-count">01</span><span class="flow-icon">↧</span><span class="flow-label">INGEST</span></button>
<button class="flow-node" data-stage="1" aria-pressed="false"><span class="flow-count">02</span><span class="flow-icon">⌘</span><span class="flow-label">PROCESS</span></button>
<button class="flow-node" data-stage="2" aria-pressed="false"><span class="flow-count">03</span><span class="flow-icon">✳</span><span class="flow-label">INFER</span></button>
<button class="flow-node" data-stage="3" aria-pressed="false"><span class="flow-count">04</span><span class="flow-icon">✓</span><span class="flow-label">VALIDATE</span></button></div>
<div class="stage-info" aria-live="polite"><div><span class="stage-kicker" id="stage-kicker">01 / DOCUMENT INGESTION</span><h3 id="stage-heading">Messy inputs. Clear boundaries.</h3><p id="stage-description">PDFs, email attachments and client formats enter through a recoverable backend workflow.</p></div><span class="stage-status">ACTIVE MODULE <span class="status-breathe"></span></span></div><div class="panel-foot"><span>NOT A LIVE COMPANY SYSTEM</span><span>INTERACTIVE CONCEPT</span></div></div></div>'''

home=f'''<section class="hero section-grid"><div class="wrap hero-grid"><div class="hero-main reveal"><div class="eyebrow"><span class="eyebrow-line"></span> SOFTWARE ENGINEER · BACKEND / AI / CLOUD <span class="hero-status"><i></i> BENGALURU, INDIA</span></div>
<h1>I build systems <em>where intelligence</em> meets reality<span class="period">.</span></h1>
<p class="hero-lede">From production AI workflows to critical data migrations, I turn complex engineering problems into software people can rely on.</p>
<div class="hero-buttons"><a class="btn btn-accent" href="#work">Explore selected work {icon('arrow-up',17)}</a><a class="btn btn-outline" href="/assets/Tanmay_Agrawal_Resume.pdf" target="_blank" rel="noopener">View résumé {icon('download',17)}</a></div>
<div class="hero-meta"><span><strong>NOW</strong> SDE (Backend) at Pibit.ai</span><span class="meta-slash">/</span><span><strong>FOCUS</strong> Production-grade software</span></div></div><div class="hero-aside reveal">{hero_diagram}</div></div><span class="hero-vertical" aria-hidden="true">DESIGN → IMPLEMENT → OPERATE</span></section>
<section class="proof-band" aria-label="Areas of focus"><div class="wrap proof-grid"><span>PRODUCTION AI WORKFLOWS <b>↗</b></span><span>CRITICAL DATA MIGRATIONS <b>↗</b></span><span>EVENT-DRIVEN BACKENDS <b>↗</b></span><span>ENTERPRISE ENGINEERING <b>↗</b></span></div></section>
<section class="work-section section" id="work"><div class="wrap"><div class="section-header"><div><div class="eyebrow muted"><span class="eyebrow-line"></span> 01 / SELECTED ENGINEERING WORK</div><h2>Proof of <span class="outline-word">work.</span></h2><p class="section-intro">Production problems, the decisions behind them, and the boundaries of what I personally built. Case studies are deliberately sanitized to respect employer and client confidentiality.</p></div><div class="filter-controls" role="group" aria-label="Filter work"><button class="filter active" data-filter="all" aria-pressed="true">All work</button><button class="filter" data-filter="ai" aria-pressed="false">AI</button><button class="filter" data-filter="systems" aria-pressed="false">Systems</button><button class="filter" data-filter="product" aria-pressed="false">Product</button></div></div><div class="work-grid">{WORKCARDS}</div></div></section>
<section class="approach-section section" id="approach"><div class="wrap"><div class="eyebrow muted"><span class="eyebrow-line"></span> 02 / HOW I WORK</div><div class="approach-grid"><div class="approach-title"><h2>Architecture is a responsibility<span class="period">.</span></h2><p>Not a diagram that ends at deployment. I follow the work through testing, production behavior and the people depending on it.</p><div class="quote-mark">“</div><blockquote>Design for failure. Validate the numbers. Stay close to the people using the system.</blockquote></div><div class="approach-items"><article class="approach-item"><span class="item-num">01</span><div><h3>Understand the actual problem.</h3><p>Talk to operations, product and clients. Find the constraint underneath the ticket before reaching for a solution.</p></div></article><article class="approach-item"><span class="item-num">02</span><div><h3>Build for the real conditions.</h3><p>Async processing, caching, isolation and recovery matter because real documents, client traffic and failures are rarely tidy.</p></div></article><article class="approach-item"><span class="item-num">03</span><div><h3>Take the change into production.</h3><p>Review the implementation, test against representative data, watch the rollout and verify that downstream numbers still make sense.</p></div></article><article class="approach-item"><span class="item-num">04</span><div><h3>Use AI deliberately.</h3><p>Use AI-assisted tooling to accelerate implementation and testing while owning the architecture, review, correctness and final engineering decisions.</p></div></article></div></div></div></section>
<section class="metrics-strip"><div class="wrap metrics-grid"><div><strong>60–70K<span>≈</span></strong><p>Client records processed via internship automation, across batches</p></div><div><strong>4</strong><p>Interns mentored alongside independently owned projects</p></div><div><strong>15m <span>→</span> ~2m</strong><p>Observed PDF workflow improvement for affected processing runs</p></div></div></section>
<section class="about-section section" id="about"><div class="wrap about-grid"><div class="about-lead"><div class="eyebrow muted"><span class="eyebrow-line"></span> 03 / ABOUT THE ENGINEER</div><h2>Deep in the code. <em>Close to the business.</em></h2><p>I'm Tanmay, a backend-focused Software Development Engineer working on AI-enabled applications and enterprise software at Pibit.ai. I move between system architecture, database and cloud engineering, production issues, and direct conversations with the people relying on our products.</p><p>My earlier paid full-stack project connected an air-curtain fleet through React, AWS IoT and DynamoDB. Today, my work spans production AI workflows, client integrations, billing-sensitive migrations and mentoring fellow engineers.</p><div class="about-buttons">{social_link(LINKEDIN,'LinkedIn','linkedin')}{social_link(GITHUB,'GitHub','github')}</div></div>
<div class="stack-card"><div class="stack-head"><span>WORKING TOOLKIT</span><span class="stack-symbol">✳</span></div><div class="stack-row"><span>BACKEND</span><p>Python · FastAPI · Celery · REST APIs · Node.js</p></div><div class="stack-row"><span>AI & DOCUMENTS</span><p>Azure OpenAI · Azure OCR · Structured validation</p></div><div class="stack-row"><span>CLOUD</span><p>AWS Lambda · S3 · SQS · EC2 · Fargate · CloudFormation</p></div><div class="stack-row"><span>DATA</span><p>PostgreSQL · RDS · Redis · DynamoDB</p></div><div class="stack-row"><span>ENGINEERING</span><p>Docker · Pytest · LocalStack · GitHub Actions · Sentry</p></div><div class="stack-foot">SELECTED TECHNOLOGIES I HAVE USED HANDS-ON</div></div></div></section>
<section class="timeline-section section"><div class="wrap"><div class="eyebrow muted"><span class="eyebrow-line"></span> 04 / THE JOURNEY</div><div class="timeline-heading"><h2>Work that <em>compounds.</em></h2><p>From building my first real-world IoT platform to owning complex production backend systems.</p></div><div class="timeline"><div class="timeline-row"><span class="tl-date">JUL 2025 — NOW</span><div class="tl-dot"></div><div class="tl-content"><h3>Software Development Engineer <span>↗</span></h3><p class="tl-company">Pibit.ai · Bengaluru</p><p>Architecture, production AI integration, cross-region migrations, database performance, webhook modernization and operational reliability. Mentored four interns and partnered directly with product, operations and clients.</p></div></div><div class="timeline-row"><span class="tl-date">AUG 2024 — JUN 2025</span><div class="tl-dot"></div><div class="tl-content"><h3>Software Development Engineer Intern</h3><p class="tl-company">Pibit.ai · Bengaluru</p><p>Enterprise integrations, document-processing and AI workflows, and an EC2/Selenium automation processing approximately 60–70K records across client batches.</p></div></div><div class="timeline-row"><span class="tl-date">APR — JUN 2024</span><div class="tl-dot"></div><div class="tl-content"><h3>Full Stack Web Developer · Paid Project</h3><p class="tl-company">Mitzwah Engg Inc. India</p><p>Independently developed a nationally deployed air-curtain portal with React, Node.js, AWS IoT, MQTT and DynamoDB.</p></div></div><div class="timeline-row"><span class="tl-date">2025</span><div class="tl-dot"></div><div class="tl-content"><h3>B.Tech, Computer Science & Engineering</h3><p class="tl-company">ABES Engineering College · CGPA 8.01/10</p><p>Also recognized as Pibit.ai's Top Performer of 2025; earned first place at the national-level ACM-ACPC programming competition.</p></div></div></div></div></section>
<section class="contact-section section" id="contact"><div class="wrap contact-grid"><div class="contact-main"><div class="eyebrow"><span class="eyebrow-line"></span> 05 / LET'S CONNECT</div><h2>Have a problem <em>worth solving?</em></h2><p>I'm interested in ambitious backend and applied AI engineering problems—and in working with teams that care about reliability as much as delivery.</p><div class="contact-ctas"><a class="btn btn-dark" href="mailto:{EMAIL}?subject=Hello%20Tanmay%20%E2%80%94%20Let%27s%20connect">Start a conversation {icon('arrow-up',18)}</a><button class="copy-email" type="button" data-email="{EMAIL}">{icon('copy',17)}<span>Copy email</span></button></div></div><div class="contact-aside"><span class="contact-asterisk">✳</span><span>LET'S BUILD SOMETHING<br>THAT ACTUALLY WORKS.</span></div></div></section>'''

(DIST/'index.html').write_text(base('Tanmay Agrawal | Backend, Production AI & Cloud Engineer','Tanmay Agrawal is a backend software engineer building production AI workflows, enterprise APIs, reliable distributed services and cloud systems.',home),encoding='utf-8')

for x in CASES:
 d=DIST/'work'/x['slug']; d.mkdir(parents=True,exist_ok=True)
 case=f'''<section class="case-hero section-grid"><div class="wrap"><a href="/#work" class="back-link">{icon('back',17)} All selected work</a><div class="eyebrow case-eyebrow"><span class="eyebrow-line"></span>{x['number']} / {escape(x['category'])} <span class="case-year">{escape(x['year'])}</span></div><h1>{escape(x['name'])}<span class="period">.</span></h1><p class="case-lede">{escape(x['short'])}</p><div class="case-hero-meta"><div><span>MY ROLE</span><strong>{escape(x['contribution'])}</strong></div><div><span>SELECTED TOOLS</span><strong>{' · '.join(escape(t) for t in x['stack'])}</strong></div></div></div></section><section class="case-content section"><div class="wrap case-columns"><aside class="case-aside"><span class="side-number">{x['number']} / 06</span><div class="sidebar-divider"></div><p>Real engineering work, shared at a level that respects company and client confidentiality.</p><a href="mailto:{EMAIL}?subject=Let%27s%20discuss%20your%20engineering%20work" class="sidebar-link">Discuss the work {icon('arrow-up',15)}</a></aside><div class="case-main"><div class="case-section"><span class="case-label">THE CHALLENGE</span><h2>Why this mattered</h2><p>{escape(x['problem'])}</p></div><div class="case-section"><span class="case-label">THE ENGINEERING</span><h2>What I did</h2><div class="step-list">{''.join(f'<article class="step"><span>0{i+1}</span><div><h3>{escape(s)}</h3><p>{escape(v)}</p></div></article>' for i,(s,v) in enumerate(x['approach']))}</div></div><div class="case-section outcome-section"><span class="case-label">THE OUTCOME</span><h2>What changed</h2><p>{escape(x['result'])}</p></div><div class="ownership-note"><strong>Ownership, precisely.</strong><p>{escape(x['responsibility'])}</p></div><div class="next-work"><span>KEEP EXPLORING</span><div class="next-work-links"><a href="/work/{CASES[(CASES.index(x)-1)%len(CASES)]['slug']}/">{icon('back',18)} Previous</a><a href="/work/{CASES[(CASES.index(x)+1)%len(CASES)]['slug']}/">Next case study {icon('arrow',18)}</a></div></div></div></div></section>'''
 (d/'index.html').write_text(base(x['name']+' | Tanmay Agrawal',x['short'],case,page='case',canonical=f"/work/{x['slug']}/"),encoding='utf-8')

(ASSETS/'favicon.svg').write_text('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#0d171a"/><text x="11" y="43" font-family="Arial,Helvetica,sans-serif" font-size="31" font-weight="800" letter-spacing="-4" fill="#f4f4ee">t<tspan fill="#bdf484">.</tspan>a</text></svg>''',encoding='utf-8')
(DIST/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {SITE_URL}/sitemap.xml\n',encoding='utf-8')
(DIST/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ''.join(f'  <url><loc>{xml_escape(SITE_URL + path)}</loc></url>\n' for path in ['/']+[f"/work/{x['slug']}/" for x in CASES]) + '</urlset>\n',encoding='utf-8')
(DIST/'.nojekyll').touch()
(DIST/'404.html').write_text(base('Page not found | Tanmay Agrawal','This page is not available. Return to the portfolio.','<section class="case-hero"><div class="wrap"><p class="eyebrow">404 / NOT FOUND</p><h1>Wrong turn.<span class="period"> Right direction.</span></h1><p class="case-lede">That page does not exist.</p><a class="btn btn-accent" href="/">Return home →</a></div></section>',page='404'),encoding='utf-8')
print('Built pages:',len(list(DIST.rglob('*.html'))))
